# Generated by Django 5.2.5 on 2025-08-15 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('customers_debt', 'Clientes con Deuda'), ('payments_history', 'Historial de Pagos'), ('available_lots', 'Lotes Disponibles'), ('sales_summary', 'Resumen de Ventas'), ('financial_overview', 'Resumen Financiero'), ('pending_installments', 'Cuotas Pendientes'), ('monthly_collections', 'Cobranzas Mensuales'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos del Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generado el')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx')],
            },
        ),
    ]
