# Generated by Django 4.2.10 on 2025-09-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50, verbose_name='Manzana')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta (Saldo Inicial)')),
                ('initial_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pago Inicial (Enganche)')),
                ('financing_months', models.PositiveIntegerField(default=0, verbose_name='Meses de Financiamiento')),
                ('payment_day', models.PositiveIntegerField(default=15, help_text='Día del mes en que vencen las cuotas (1-31)', verbose_name='Día de Vencimiento Mensual')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('liquidado', 'Liquidado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contrato PDF')),
                ('contract_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='customers.customer', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['block', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='LoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lotes.lote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Lote',
                'verbose_name_plural': 'Historiales de Lotes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('block', 'lot_number'), name='unique_lote'),
        ),
    ]
