# Generated by Django 4.2.10 on 2025-08-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50, verbose_name='Manzana')),
                ('lot_number', models.CharField(max_length=50, verbose_name='Número de Lote')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('desarrollo', 'En Desarrollo')], default='disponible', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='customers.customer', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['block', 'lot_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('block', 'lot_number'), name='unique_lote'),
        ),
    ]
