# Generated by Django 4.2.10 on 2025-09-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='financing_months',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='initial_payment',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='payment_day',
        ),
        migrations.AlterField(
            model_name='lote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta'),
        ),
    ]
