# Generated by Django 4.2.10 on 2025-08-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lotes.lote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Lote',
                'verbose_name_plural': 'Historiales de Lotes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
