# Generated by Django 4.2.10 on 2025-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_lotehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='financing_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses de Financiamiento'),
        ),
        migrations.AddField(
            model_name='lote',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pago Inicial (Enganche)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta (Saldo Inicial)'),
        ),
    ]
