# Generated by Django 5.2.5 on 2025-08-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_lote_financing_months_lote_initial_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
