# Generated by Django 5.2.5 on 2025-08-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_lote_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='payment_day',
            field=models.PositiveIntegerField(default=15, help_text='Día del mes en que vencen las cuotas (1-31)', verbose_name='Día de Vencimiento Mensual'),
        ),
    ]
