# Generated by Django 5.2.5 on 2025-08-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_lote_payment_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='expiration_date',
        ),
    ]
