# Generated by Django 4.2.10 on 2025-09-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_remove_lote_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Contrato'),
        ),
        migrations.AddField(
            model_name='lote',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contrato PDF'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('liquidado', 'Liquidado')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
