# Generated by Django 4.2.10 on 2025-09-06 22:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('suspended', 'Suspendida')], default='active', help_text='Estado actual del contrato de venta', max_length=20, verbose_name='Estado')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Precio total acordado para la venta del lote', max_digits=12, verbose_name='Precio de Venta')),
                ('initial_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del pago inicial realizado', max_digits=12, verbose_name='Pago Inicial')),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se realizó la venta', verbose_name='Fecha de Venta')),
                ('contract_date', models.DateField(blank=True, help_text='Fecha oficial del contrato firmado', null=True, verbose_name='Fecha del Contrato')),
                ('cancellation_date', models.DateTimeField(blank=True, help_text='Fecha en que se canceló la venta', null=True, verbose_name='Fecha de Cancelación')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago total', null=True, verbose_name='Fecha de Finalización')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la venta', verbose_name='Notas')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Razón por la cual se canceló la venta', verbose_name='Motivo de Cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Cliente que compra el lote', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='customers.customer', verbose_name='Cliente')),
                ('lote', models.ForeignKey(help_text='Lote que se está vendiendo', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('lote',), name='unique_active_sale_per_lote'),
        ),
    ]
