# Generated by Django 4.2.10 on 2025-09-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='financing_months',
            field=models.PositiveIntegerField(default=12, help_text='Número de meses para el financiamiento del lote', verbose_name='Meses de Financiamiento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_day',
            field=models.PositiveIntegerField(default=15, help_text='Día del mes en que vencen las cuotas (1-31)', verbose_name='Día de Pago'),
        ),
    ]
