# Generated by Django 4.2.10 on 2025-09-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_venta_financing_months_venta_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='contract_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF del contrato firmado', null=True, upload_to='contracts/', verbose_name='PDF del Contrato'),
        ),
    ]
