# Generated by Django 4.2.10 on 2025-09-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venta_contract_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='schedule_start_date',
            field=models.DateField(blank=True, help_text='Fecha desde la cual comenzarán a generarse las cuotas. Si no se especifica, se usa el mes actual.', null=True, verbose_name='Fecha de Inicio del Cronograma'),
        ),
    ]
