# Generated by Django on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_venta_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='adenda_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF de la adenda del contrato (opcional)', null=True, upload_to='contracts/adendas/', verbose_name='PDF de la Adenda'),
        ),
        migrations.AddField(
            model_name='venta',
            name='escritura_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF de la escritura pública (opcional)', null=True, upload_to='contracts/escrituras/', verbose_name='PDF de la Escritura'),
        ),
    ]
