# Generated by Django 4.2.10 on 2025-09-06 22:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Imagen del Comprobante')),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Cuota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Pago')),
                ('payment_date', models.DateTimeField(verbose_name='Fecha de Pago')),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], default='transferencia', max_length=20, verbose_name='Método de Pago')),
                ('payment_type', models.CharField(choices=[('initial', 'Pago Inicial/Enganche'), ('installment', 'Cuota Mensual')], default='installment', max_length=20, verbose_name='Tipo de Pago')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Operación')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Operación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_legacy', to='customers.customer', verbose_name='Cliente')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_legacy', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Monto original programado al crear el cronograma', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Original')),
                ('scheduled_amount', models.DecimalField(decimal_places=2, help_text='Monto actual a pagar (puede ser diferente al original)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Programado Actual')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Pagado')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Fecha en que se realizó el pago', null=True, verbose_name='Fecha de Pago')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Imagen del Comprobante')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Operación')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Operación')),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('partial', 'Pago Parcial'), ('forgiven', 'Absuelto')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_forgiven', models.BooleanField(default=False, help_text='Marca si esta cuota ha sido perdonada/regalada', verbose_name='Cuota Absuelto')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre cambios o situaciones especiales', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payments', models.ManyToManyField(blank=True, help_text='Pagos que se han aplicado a esta cuota del cronograma', related_name='payment_schedules', to='payments.payment', verbose_name='Pagos Asociados')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_schedule_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cronograma de Pago',
                'verbose_name_plural': 'Cronogramas de Pago',
                'ordering': ['venta', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('payment_day', models.PositiveIntegerField(default=13, help_text='Día del mes en que vence cada cuota (1-31)', verbose_name='Día de Pago Mensual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pagos', to='sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Plan de Pagos',
                'verbose_name_plural': 'Planes de Pagos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentplan', verbose_name='Plan de Pagos'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.venta', verbose_name='Venta'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.UniqueConstraint(fields=('venta', 'installment_number'), name='unique_venta_installment'),
        ),
    ]
