# Generated by Django 4.2.10 on 2025-09-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='installment_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_plan',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_payments', to='payments.paymentschedule', verbose_name='Cronograma de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.venta', verbose_name='Venta'),
        ),
    ]
