# Generated by Django 4.2.10 on 2025-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Cuota'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Imagen del Comprobante'),
        ),
    ]
