# Generated by Django 4.2.10 on 2025-09-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
