# Generated by Django 5.2.5 on 2025-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_installment_number_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Operación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Operación'),
        ),
    ]
