# Generated by Django 5.2.5 on 2025-08-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_lote_expiration_date'),
        ('payments', '0003_payment_receipt_date_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('payment_day', models.PositiveIntegerField(default=13, help_text='Día del mes en que vence cada cuota (1-31)', verbose_name='Día de Pago Mensual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='lotes.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Plan de Pagos',
                'verbose_name_plural': 'Planes de Pagos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentplan', verbose_name='Plan de Pagos'),
        ),
    ]
