# Generated by Django 4.2.10 on 2025-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='boleta_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Boleta de Pago'),
        ),
    ]
