# Generated by Django 4.2.10 on 2025-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentschedule_boleta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='boleta_image',
            field=models.ImageField(blank=True, null=True, upload_to='boleta_pagos/', verbose_name='Boleta de Pago'),
        ),
    ]
