# Generated by Django 5.2.5 on 2025-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_due_date_paymentplan_payment_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'Pago Inicial/Enganche'), ('installment', 'Cuota Mensual')], default='installment', max_length=20, verbose_name='Tipo de Pago'),
        ),
    ]
