# Generated by Django 4.2.10 on 2025-09-25 16:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentschedule_boleta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='scheduled_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto actual a pagar (puede ser diferente al original)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Programado Actual'),
        ),
    ]
