# Generated by Django 4.2.10 on 2025-08-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Fecha de Pago'),
        ),
    ]
