# Generated by Django 5.2.5 on 2026-01-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentschedule_scheduled_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='boleta_image',
            field=models.ImageField(blank=True, null=True, upload_to='boleta_pagos/', verbose_name='Boleta de Pago'),
        ),
    ]
