# Generated by Django 4.2.10 on 2026-02-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_boleta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='is_refinanced',
            field=models.BooleanField(default=False, help_text='Marca si esta cuota ha sido refinanciada (monto distribuido a otras cuotas)', verbose_name='Cuota Refinanciada'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('partial', 'Pago Parcial'), ('forgiven', 'Absuelto'), ('refinanced', 'Refinanciado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
