# Generated by Django 4.2.10 on 2025-09-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0007_remove_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
