"""
Django settings for villanueva_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')


def _env_list(name: str, default: str = '') -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-656^oe7&+v9_kb=l=yg(ce8mi&-gj+pgfpq40irnp=xcs&fc$s',
)

DEBUG = _env_bool('DEBUG', default=True)

_allowed_hosts = _env_list('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = _allowed_hosts if _allowed_hosts else ['*']

PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', '').rstrip('/')
IP_BASE_URL = os.environ.get('IP_BASE_URL', '')


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',  # Comentado para evitar conflictos con el frontend
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',

    #local apps
    'users',
    'customers',
    'lotes',
    'sales',
    'payments',
    'reports',
    'reminders',
    'dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'villanueva_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'villanueva_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'villanueva_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_LOCATION= 'static'
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploads) — ruta relativa para nginx/Traefik en producción
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Forzar URLs relativas para archivos de media
USE_ABSOLUTE_URLS = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth settings
AUTH_USER_MODEL = 'users.User'

#CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://frontend:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://backend:8000",
    "http://0.0.0.0:8000",
    "http://0.0.0.0:5173",
    "http://0.0.0.0:80",
    "http://192.168.100.4:8000",
    "http://192.168.100.4:5173",
]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://frontend:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://backend:8000",
    "http://0.0.0.0:8000",
    "http://0.0.0.0:5173",
    "http://0.0.0.0:80",
    "http://192.168.100.4:8000",
    "http://192.168.100.4:5173",
]



def _origin_variants(base: str) -> list[str]:
    base = base.rstrip('/')
    origins = {base}
    if base.startswith('https://'):
        origins.add(base.replace('https://', 'http://', 1))
    elif base.startswith('http://'):
        origins.add(base.replace('http://', 'https://', 1))
    else:
        origins.update({f'http://{base}', f'https://{base}', f'http://{base}:80', f'http://{base}:8000'})
    return list(origins)


if PUBLIC_SITE_URL:
    for origin in _origin_variants(PUBLIC_SITE_URL):
        CORS_ALLOWED_ORIGINS.append(origin)
        CSRF_TRUSTED_ORIGINS.append(origin)

if IP_BASE_URL:
    for origin in _origin_variants(f'http://{IP_BASE_URL}' if '://' not in IP_BASE_URL else IP_BASE_URL):
        CORS_ALLOWED_ORIGINS.append(origin)
        CSRF_TRUSTED_ORIGINS.append(origin)

USE_HTTPS = _env_bool(
    'USE_HTTPS',
    default=PUBLIC_SITE_URL.startswith('https://'),
)

if not DEBUG:
    USE_X_FORWARDED_HOST = True
    if USE_HTTPS:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True




# Configuraciones adicionales para CORS en Docker
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',    
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25  # Devuelve 25 clientes por página | Puede ser ajustado según sea necesario | 
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Villanueva API',
    'DESCRIPTION': 'API para la gestión de lotes y pagos',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
